### ISSUE TITLE
Is this still running , 

### ISSUE THREAD

**Issue by ChathuraMalinga** [akaniklaus/channelmanager#5]
Is this still running , ?

**Comment by italasso** [comment]
I wish it was. I'm actually willing to finance some of the further creation.

**Comment by akaniklaus** [comment]
Hello, the project is discontinued unfortunately.

**Comment by ChathuraMalinga** [comment]
@akaniklaus  I like continue this project and while I'm researching, I got this,    that would be great if would you be able to share any documentation. if any, also if there is any one who like to work with this,please contact me, thank you

**Comment by akaniklaus** [comment]
I don't have any additional documentation except for Certification Process (May 26, 2015).pdf that I previously uploaded to the repository. I don't also know anybody that you can collaborate with.

**Comment by ChathuraMalinga** [comment]
anyway thank you for the code @akaniklaus

**Comment by italasso** [comment]
@ChathuraMalinga what kind of work are you planning to do? I already own a PMS and I need to create a Channel Manager module for it.

**Comment by ChathuraMalinga** [comment]
@italoroldo Thank you for the rep, First step is Developing OTA Channel Manager , For that I know, need to get connected with OTAs (booking.com, Agoda.com .. etc.. APIs),  I use OpenTravel as it needs to be in a stranded level, yet OYAs have there own APIs, and also have to work on that too, I'm Still doing research and development, to make it happen.

PMS -  That;s Good, Let me know more details.

**Comment by italasso** [comment]
Hello Chathura. I already started the process, that means I have full access to at least Booking.com , Expedia and Despegar.com developers partner/central. I also own 2 hotels in Brazil and I want to create my own channel manager so I can offer other hotels to use later.  I'm planning to go to Serbia for a few months because I know a team of very good developers there to develop it for me. What kind of collaboration do you think we could do on this project? Thank u, looking forward to hearing from you. Let's keep via e-mail please: italoroldo@gmail.com.

**Comment by ChathuraMalinga** [comment]
> Hello Chathura. I already started the process, that means I have full access to at least Booking.com , Expedia and Despegar.com developers partner/central. I also own 2 hotels in Brazil and I want to create my own channel manager so I can offer other hotels to use later. I'm planning to go to Serbia for a few months because I know a team of very good developers there to develop it for me. What kind of collaboration do you think we could do on this project? Thank u, looking forward to hearing from you. Let's keep via e-mail please: [italoroldo@gmail.com](mailto:italoroldo@gmail.com).

thank you Email sent,

**Comment by shiva-rnm** [comment]
> @akaniklaus I like continue this project and while I'm researching, I got this, that would be great if would you be able to share any documentation. if any, also if there is any one who like to work with this,please contact me, thank you

Hi, i would like to work on channel manager API task. please connect with me on shivakumar.rnm at gmail dot com

**Comment by shiva-rnm** [comment]
> @italoroldo Thank you for the rep, First step is Developing OTA Channel Manager , For that I know, need to get connected with OTAs (booking.com, Agoda.com .. etc.. APIs), I use OpenTravel as it needs to be in a stranded level, yet OYAs have there own APIs, and also have to work on that too, I'm Still doing research and development, to make it happen.
> 
> PMS - That;s Good, Let me know more details.

Hi, i would like to work on channel manager API task. please connect with me on shivakumar.rnm at gmail dot com

**Comment by codemasterlike** [comment]
I also like to collaborate with this project, please include me for development the project.
My email hongnhatthong at gmail.com
